# NOTE: *must* import with:
#
# conda env create -f ./environment.yml -p ./.conda/collaborative-learning-dev
#
# command must be launched in the agent folder.
channels:
  - defaults
dependencies:
  - python=3.11
  - pybind11
  - tensorflow=2.12.0
  - pip
  - pandas
  - matplotlib
  - pip:
    - tf-agents[reverb] == 0.16.0