# NOTE: *must* import with:
#
# conda env create -f ./environment.yml -p ./.conda/collaborative-learning-dev
#
# command must be launched in the agent folder.

# NOTE: tensorflow and tf-agents versions must match according to the following matrix:
# https://www.tensorflow.org/agents/overview#releases

channels:
  - defaults
dependencies:
  - python=3.11
  - pybind11
  - tensorflow=2.12.0
  - pip
  - pandas
  - matplotlib
  - pip:
    - tf-agents[reverb] == 0.16.0